session_name: project
windows:
  - window_name: dev
    focus: True
    panes:
      - vim
  - window_name: sync
    layout: main-vertical
    options:
      main-pane-width: 170
    panes:
      - shell_command:
        - tig
        focus: True
      -
  - window_name: run
    panes:
      -
